[package]
name = "evaluate-math"
version = "0.0.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2.0.0-alpha.7"
napi-derive = "2.0.0-alpha.7"
meval = "0.2.0"

[build-dependencies]
napi-build = "1"

[profile.release]
lto = true
